examples/server/main.go

`FromContext` is the newer method for accessing a transaction from within an http handler.
These examples use a mix of type casting and `FromContext`. This PR makes them consistent.
I propose that New Relic update all documentation and examples removing type casting in favor of  `FromContext` to help prevent customers from experiencing issues related to the old type cast method.
Details regarding the type of problem type casting creates and why `FromContext` is strictly superior can be found in the following github issue for a piece of HTTP middleware that is incompatible with many newrelic integrations due to the widespread use of type casting for transaction retrieval: https://github.com/kevburnsjr/microcache/issues/10

Updates examples to retrieve transaction using FromContext

---

v3/integrations/nrmysql/go.mod

* match `go` version to `mysql` driver version (1.10)
* bump `github.com/go-sql-driver/mysql` to `v1.5.0` (now supports modules)
* bump `github.com/newrelic/go-agent/v3` to `v3.4.0`

Update dependecy versions for nrmysql

---

v3/newrelic/collector.go
v3/newrelic/collector_test.go
v3/newrelic/internal_app.go
v3/newrelic/transport.go
v3/newrelic/transport_1_12.go

This pre-release branch does two things to improve the agent experience when sending data to the New Relic backend times out.
First, instead of dropping data on the floor, we will save it and attempt to resend it with the next harvest cycle. Note that because the agent has internal limits to the amount of data it holds, if the timeouts happen for a prolonged period and your application is collecting a lot of events, some could still get dropped.
Second, the agent will stop using the `http.DefaultTransport` for communication with the New Relic backend. This change will help address https://github.com/golang/go/issues/33006 which can cause all outbound requests using the same transport to hang, irregardless of the host they are attempting to connect with.

Improve experience when sending data times out.

---

v3/newrelic/internal_txn.go
v3/newrelic/sql_driver.go
v3/newrelic/sql_driver_test.go
v3/newrelic/transaction.go

Addressing https://github.com/newrelic/go-agent/issues/138
If a SQL driver returned `driver.ErrSkip`, we were ending up with with orphaned datastore spans. This change conditionally creates the spans only if `driver.ErrSkip` is not returned.

Fix parentage of datastore segments

---

.github/ISSUE_TEMPLATE/bug-report---.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement-request---.md
.github/ISSUE_TEMPLATE/troubleshooting.md

Following https://github.com/aprilla/github-sandbox/tree/master/.github/ISSUE_TEMPLATE to add templates to how users create new issues.

Add issues template.

---

v4/newrelic/segments.go
v4/newrelic/segments_test.go

This pull request implements `DatastoreSegment`, `ExternalSegment`, and `MessageProducerSegment`. The biggest challenge here was deciding on the name for each of these span types. I did my best to follow the OpenTelemetry specs for naming.
* [Semantic conventions for database client calls](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md)
* [Semantic conventions for HTTP spans](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name)
* [Semantic conventions for messaging systems](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#span-name)

Implement other segment types.

---

build-script.sh
v3/newrelic/trace_observer_test.go

There are two fixes in this Pull Request.
First is the fix for the flakey failing infinite tracing test. That test is ensuring that when reconnecting to the trace observer host after receiving an OK response does not use a backoff. To test that we want to ensure that we connect once, disconnect, then immediately reconnect a second time. We do not really care if the spans are actually received or not. So, I changed the check to ensure we are connecting, not receiving spans. This seems to have fixed the issue as I ran the tests at least 3-4 times and they never failed.
Second is an update grpc made this very morning in deprecating go1.9. According to their documentation they only support go1.11 and above (or maybe go1.12 and above?), however, it seems that go1.10 builds just fine. I want to …

Wait for connection rather than span receive.

---

build-script.sh
v4/go.mod
v4/newrelic/application.go
v4/newrelic/segments_test.go
v4/newrelic/transaction.go

With every span we need to also include the [Span Kind](https://pkg.go.dev/go.opentelemetry.io/otel@v0.9.0/api/trace?tab=doc#SpanKind). Unfortunately right now, OTel's Go implementation only supports setting the `SpanKind` at span start time. Since we cannot know which type of segment `txn.StartSegmentNow` is being called for, this will not work for us. This PR sets all the spans we create to be "internal" spans.
I spoke with @MrAlias about this and he opened an issue https://github.com/open-telemetry/opentelemetry-go/issues/988 that would mean we could set the `SpanKind` at either start _or_ end. Once that work is done, we need to circle back and implement the span kind for each span. We'll need to be sure to set the root span to the "server" type iff the `txn.SetWebRequest` API has been …

Set SpanKind to internal for all spans.

---

v4/newrelic/application.go
v4/newrelic/config.go
v4/newrelic/instrumentation.go
v4/newrelic/segments.go
v4/newrelic/segments_test.go
v4/newrelic/transaction.go
v4/newrelic/transaction_test.go

This adds DT support to the shim by implementing the functions `InsertDistributedTraceHeaders` and `AcceptDistributedTraceHeaders`, using the TraceContext injector and extractor OpenTelemetry provides.
The implementation for `InsertDistributedTraceHeaders` is straight-forward and uncontroversial.
Things get a bit messy with `AcceptDistributedTraceHeaders` though. OpenTelemetry requires that the inbound headers were received _before_ the trace was started, whereas the Go agent requires the opposite, namely that a transaction was started _before_ inbound headers were received. We cannot call `AcceptDistributedTraceHeaders` before a transaction was started. I don't see a possibility to do a 1:1 mapping of one solution to another.
The best solution I could come up with is starting a new trace …

Add DT support to the shim

---

v4/newrelic/application.go
v4/newrelic/application_test.go

Make sure that when using `(*Application)(nil)` or `&Application{}` that all methods do not panic.

Support nil and empty Applications.

---

.github/workflows/ci.yaml
v4/integrations/nrgrpc/nrgrpc_client_test.go
v4/integrations/nrmicro/nrmicro.go
v4/integrations/nrmicro/nrmicro_test.go
v4/integrations/nrnats/nrnats.go
v4/integrations/nrnats/test/nrnats_test.go
v4/integrations/nrstan/nrstan.go
v4/integrations/nrstan/test/nrstan_test.go

This pull request re-enables grpc, micro, and nats/stan testing. A few small changes were required in each in order to get it working. I left comments in those places.

Reenable tests that required DT implementation.

---

v4/integrations/nrawssdk-v1/nrawssdk_test.go
v4/integrations/nrawssdk-v2/nrawssdk_test.go
v4/integrations/nrecho-v3/nrecho_test.go
v4/integrations/nrecho-v4/nrecho_test.go
v4/integrations/nrgin/nrgin_test.go
v4/integrations/nrgorilla/nrgorilla_test.go
v4/integrations/nrgrpc/nrgrpc_client_test.go
v4/integrations/nrgrpc/nrgrpc_server_test.go
v4/integrations/nrhttprouter/nrhttprouter_test.go
v4/integrations/nrmicro/nrmicro_test.go
v4/integrations/nrmongo/nrmongo_test.go
v4/integrations/nrnats/test/nrnats_test.go
v4/integrations/nrstan/test/nrstan_test.go
v4/internal/expect.go
v4/internal/integrationsupport/integrationsupport.go
v4/internal/integrationsupport/integrationsupport_test.go
v4/internal/otel_expect.go

This pull request implements `ExpectSpanEvents` for use when testing integration packages. It also removes `ExpectTxnEvents` because those are essentially just span events anyway, so the APIs have been combined.
I'd love your feedback on the use of all the `internal.Match*` fields. I'd like your thoughts on what the best user experience of these would be.

Implement ExpectSpanEvents.

---

v4/internal/otel_expect.go

This pull request implements `ExpectTxnMetrics`. We will not be implementing any metrics during this current project. However, there is still information that we can infer from the usage of this expecter. We know that there will be a root span with the given name that has no span parent. In the future when we implement span kind, we can use the `IsWeb` field to determine the span kind of the root span.

Implement ExpectTxnMetrics.

---

v4/newrelic/transaction.go

When starting a segment, we should be using the tracer from the application.

Access tracer from the application.

---

v4/integrations/nrawssdk-v1/nrawssdk_test.go
v4/integrations/nrawssdk-v2/nrawssdk_test.go
v4/integrations/nrecho-v3/nrecho_test.go
v4/integrations/nrecho-v4/nrecho_test.go
v4/integrations/nrgin/nrgin_test.go
v4/integrations/nrgrpc/nrgrpc_client_test.go
v4/integrations/nrgrpc/nrgrpc_server_test.go
v4/integrations/nrhttprouter/nrhttprouter_test.go
v4/integrations/nrmicro/nrmicro_test.go
v4/integrations/nrmongo/nrmongo_test.go
v4/integrations/nrnats/test/nrnats_test.go
v4/integrations/nrstan/test/nrstan_test.go
v4/internal/expect.go
v4/internal/integrationsupport/integrationsupport_test.go
v4/internal/otel_expect.go
v4/newrelic/segments.go
v4/newrelic/segments_test.go
v4/newrelic/transaction.go
v4/newrelic/transaction_test.go

Implements all `*.AddAttribute` APIs and tests to make sure those APIs work as expected.
What is not included here is testing for attributes in integration packages. Because I wished to use the `app.ExpectSpanEvents` method for testing, I had to find a way to state specifically when I wanted attributes to be tested and when not. This is why I added the `SkipAttrsTest` field to `WantSpan`. Once all transaction and segment level attributes (ie we've completed work to add "intrinsic" and "agent" attributes) we should remove this field.

Support custom attributes on segments and transactions.

---

v4/newrelic/segments.go
v4/newrelic/segments_test.go

Based on the [open telemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md) for messaging. This adds attributes to our `MessageProducerSegment`s.
The specification also says we should be including `net.peer.name`, `net.peer.ip`, and `net.peer.port`. However, our `MessageProducerSegment` does not have fields for these. Adding them would mean adding two new fields onto the segment type plus updating our instrumentation for micro and nats/stan to include these. That is outside the scope of this MMF.

Add span attributes for message producer segments.

---

.github/workflows/ci.yaml
build-script.sh

Now that Go version 1.15 has been released, we should make sure to test against it.
Addresses issue #212.

Add Go version 1.15 to tests

---

v4/integrations/nrredis-v7/nrredis_test.go
v4/internal/otel_expect.go
v4/newrelic/segments.go
v4/newrelic/segments_test.go

There are three metrics that we used to create for datastore segments. With all three of those combined we can create a pretty clear picture of what the corresponding datastore span would look like. This pull request goes about making that happen.
Along the way I uncovered one issue with our datastore attributes. In the v3 agent anytime we'd see "localhost" or similar for a hostname on datastores, we'd replace it with the hostname of the local machine. I made that update here as well. And with that all the tests passed!

Improve testing from datastore metrics.

---

v3/newrelic/internal_set_web_request_test.go

A white space issue was introduced directly into master accidentally. This fixes that issue.

Fix go-fmt issue

---

CHANGELOG.md
README.md
build-script.sh
v3/integrations/nrlambda/handler.go
v3/integrations/nrlambda/handler_test.go

Merging develop into master for the release.

Release v3.9.0

---

CHANGELOG.md
v3/internal/utilization/aws.go
v3/internal/utilization/provider.go
v3/internal/utilization/provider_test.go

This implements a newer method of authentication to AWS instance metadata endpoints. 
Under IMDSv1, the agent simply called to an endpoint and received JSON with information about the instance size, availability zone, and other facts.
This newer IMDSv2 implements a session protocol. The agent calls two endpoints: one to get a session token that's valid for a specified time, and then the original endpoint with the session token to get the instance information.
As of this writing, AWS normally accepts both IMDSv1 and IMDSv2. A customer can tell AWS to only allow IMDSv2, so we're fine if we simply perform IMDSv2 calls exclusively.
Tests for these changes will need to be higher-level integration tests, since they rely on AWS services. Let me know if you think otherwise!
[Amazon's IMDSv2 …

Implement Amazon's IMDSv2

---

v3/LICENSE.txt
v3/newrelic/LICENSE.txt

Adds license file to v3/ and v3/newrelic/ subdirectories to make the
repository compatible with pkg.go.dev (in particular,
https://pkg.go.dev/github.com/google/licensecheck).
Resolves #169 https://github.com/newrelic/go-agent/issues/169

fix: Add license file to v3 and v3/newrelic

---

.github/workflows/repolinter.yml

Hello from the Open Source and Developer Advocacy team at New Relic.
This PR contains a GitHub actions workflow which runs repolinter, an automated tool to help us find and fix inconsistencies in our community files and public repositories. This PR registers a GitHub Actions workflow (`repolinter.yml`) running [repolinter-action](https://github.com/newrelic/repolinter-action). The goal of this workflow is to make our Open Source Policy enforcement more consistent and transparent for everyone.
Repolinter Action does:
* Scans the repository for Open Source policy issues using Repolinter.
* The issues this workflow scans for are determined by the ruleset specified by `with.config-url`: this ruleset will be maintained by the Open Source and Developer Advocacy team and will not change …

NR Open Source repolinter GitHub action setup

---

CHANGELOG.md
ROADMAP.md
v3/newrelic/trace_observer.go

Downgraded logging level for rebalancing messages that aren't actually errors.
Resolves #213

Change logging level for 8T rebalancing messages

---

v3/newrelic/internal_txn.go

The Go Agent is able to record errors in the case of panics. This functionality is normally turned off, see the [comments here in the source](https://github.com/newrelic/go-agent/blob/master/v3/newrelic/config.go#L104-L108).
A larger customer of ours noticed that when `cfg.ErrorCollector.RecordPanics` turned on (that is, set to `true`), the Go Agent "swallows" any stack trace that would normally be displayed by the Go runtime during a panic. This means the customer simply doesn't see stack traces anymore after panics. See issue #275. 
When a reproduction of the problem is run with this PR in place, it logs the stack trace very similarly to the original Go runtime version, but with extra frames at the top of the trace that show the Go Agent is doing its job.
Here's the output from the Go …

Log panic stack traces

---

v3/integrations/nrredis-v8/README.md
v3/integrations/nrredis-v8/example/main.go
v3/integrations/nrredis-v8/go.mod
v3/integrations/nrredis-v8/nrredis.go
v3/integrations/nrredis-v8/nrredis_example_test.go
v3/integrations/nrredis-v8/nrredis_test.go

Working on [support go-redis/redis/v8](https://github.com/orgs/newrelic/projects/37#card-47767666)
- Update version redis to go-redis/redis/v8
- Fix compatibility code example and test with go-redis/redis/v8

Added support for `v8` of go-redis/redis

---

datastore.go
v3/newrelic/datastore.go

This PR proposes to add `Aerospike` for Datastore Segment NR Transaction

Adds Aerospike in Datastore

---

v3/integrations/nrawssdk-v1/nrawssdk.go
v3/integrations/nrawssdk-v1/nrawssdk_test.go
v3/internal/awssupport/awssupport.go
v3/internal/awssupport/awssupport_test.go

https://github.com/newrelic/go-agent/issues/287
https://github.com/aws/aws-dax-go/issues/32
During the `endSegment` handler we need to check if `HTTPResponse` is populated. This prevents us from nil dereference panicking when requests to AWS services don't use HTTP such as DAX

Fixes issue with nil HttpResponse causing panics

---

CHANGELOG.md
v3/newrelic/version.go

Updates `version.go` and release notes for 3.12.0 release.
I made the assumption that changes to our internal workflow that are being adopted at the same time didn't need to be included in the release notes, but I can add that if they should also be in there.

updated version.go and release notes for 3.12.0

---

build-script.sh

This extends work done by Matt Whalen to halve the number of non-passing tests in our Go agent CI.
Some older versions of go aren't supported by the grpc-go or the x/net/http2 libraries anymore. I've made the "jail" that we put old versions of Go into a little larger, putting Go versions 1.10, 1.11, and 1.12 in there. I've also extended the jail a little to use an old version of x/net/http2 as well as the existing old version of grpc.

Getting http2 and grpc to run on old Go

---

v3/integrations/nrgrpc/go.mod
v3/integrations/nrgrpc/nrgrpc_server.go
v3/integrations/nrgrpc/nrgrpc_server_test.go

Adds error reporting to the nrgrpc integration. An error value returned from an instrumented unary or stream server call now creates an error span in the current transaction which contains the error message. Previously it only set an error status code.

fix issue 221: grpc error reporting

---

GUIDE.md

There is no command for `txn.StartExternalSegment` for both v3 version and non-v3
https://github.com/newrelic/go-agent/blob/5a0eaeb7452a247fa8bdfc5de98f7532b13738ea/segments.go#L185
https://github.com/newrelic/go-agent/blob/5a0eaeb7452a247fa8bdfc5de98f7532b13738ea/v3/newrelic/segments.go#L282
This PR updates the documentation to match the actual command provided by the package.

Fix command for StartExternalSegment

---

v3/go.mod

This slipped in while I was working on the AWS SDK V2.

Remove unneeded import

---

v3/integrations/nrb3/LICENSE.txt
v3/integrations/nrb3/go.mod

This PR fixes visibility issue for some integration documentation on the pkg.go.dev site.
Tags each integration to make pkg.go.dev notice the new version which (already) has the required license info. Also added missing files for the nrb3 integration.

update integration tags, add go.mod and license for nrb3

---

v3/go.mod
v3/newrelic/trace_context_test.go
v3/newrelic/transaction.go

When making calls to a transaction's `AcceptDistributedTraceHeaders()` you are required to pass a valid `http.Header` value holding the distributed trace headers you want the current transaction to use. However, sometimes this data arrives in a text form such as a JSON string.
This requires the programmer to perform multiple steps to build up the `http.Header` value, which can be prone to errors. I propose a convenience function that constructs this value in one step.
This PR adds two functions. `DistributedTraceHeadersFromJson()` converts a JSON representation of the trace headers to an `http.Header` object.
`AcceptDistributedTraceHeadersFromJson()` does the above plus calls `AcceptDistributedTraceHeaders()` on the result for you.
Given a JSON string such as:
```
{
"traceparent": "frob", …
```

implemented JSON distributed trace converter

---

v3/integrations/nrawssdk-v2/nrawssdk.go
v3/integrations/nrawssdk-v2/nrawssdk_test.go

https://github.com/newrelic/go-agent/issues/288#issuecomment-853978908
Allows not needing to individually wrap each AWS API call, by just leveraging the context that is present in the middleware. This allows setting up the New Relic integration once with the AWS config, and any AWS client that uses that AWS config will be automatically integrated with New Relic.
Shoutout to @HenriBeck for noticing this!

v3/integrations/nrawssdk-v2: Grab the NR Transaction from the Context when txn is not set

---

v3/newrelic/application.go

Fixes issue #296.
This adds better advice about the use of the WaitForConnection method.

added advice on usage of WaitForConnection() call

---

v3/integrations/nrgrpc/example/server/server.go
v3/integrations/nrgrpc/nrgrpc_client_test.go
v3/integrations/nrgrpc/nrgrpc_doc.go
v3/integrations/nrgrpc/nrgrpc_server.go
v3/integrations/nrgrpc/nrgrpc_server_test.go

Amends the error handling capability of the nrgrpc integration to differentiate between grpc statuses which should be reported as errors with those to be reported as warnings or informational messages. 
Rather than calling `NoticeError()` on any non-`OK` status, we call `NoticeError()` only on ones we think merit that designation. Others are reported by adding attributes to the transaction which describe the grpc status codes returned from the external service.
If the built-in default actions are not sufficient or don't match the application's needs, they may be changed by the user by changing the designation of any specific grpc error, or even by supplying a custom handler function to perform any action desired when the corresponding grpc error is seen.

Enhanced handling of grpc errors (issue #331)

---

GUIDE.md

Corrects our `GUIDE.md` document's advice on the proper `go get` command to obtain the Go agent code from github.
It now explicitly requests the v3 version.
This fixes Issue [#350](https://github.com/newrelic/go-agent/issues/350)

350 go get

---

v3/integrations/nrmongo/go.mod

The call to internal.Hostname in the nrmongodb test file was using an older version of the function on a development Mac. This is to keep that error from happening.

Get test running on Mac workstation

---

v3/integrations/nrgin/go.mod

This is to address CVE-2020-28483, and was brought to our attention by Dependabot.

Updated gin version for security reasons.

---

v3/newrelic/sqlparse/sqlparse.go
v3/newrelic/sqlparse/sqlparse_test.go

[Issue 397](https://github.com/newrelic/go-agent/issues/397)
Changes the regular expression used to recognize table name when doing simple SQL command parsing. Previously it looked for the first `FROM` but this was confused by subexpressions such as `SUBSTRING('foo' FROM x TO y)`. This changes the code to look for the last `FROM` instead.

(fix issue #397) incorrect table name reported

---

v3/internal/logger/logger.go

This PR adds a filter to messages logged through the go agent's `v3/internal/logger` facility, for all severity levels, to redact license key information from the message being logged. Since the log message may include the license key embedded in a URL string or other marshalled text, we do not try to limit the filter by parsing the strings. Rather, we simply replace the text "`license_key=`" followed by a hex digit sequence, such that the hex digits are removed.

Logger license

---

CHANGELOG.md
v3/newrelic/version.go

* Strings logged via the Go Agent's built-in logger will have strings of the form `license_key=`*hex-string* changed to `license_key=[redacted]` before they are output, regardless of severity level, where *hex-string* means a sequence of upper- or lower-case hexadecimal digits and dots ('.').
Resolves issue [416](https://github.com/newrelic/go-agent/issues/416) and related customer request.
New Relic recommends that you upgrade the agent regularly to ensure that you’re getting the latest features and performance benefits. Additionally, older releases will no longer be supported when they reach end-of-life.

Release 3.15.2

---

v3/internal/logger/logger.go

Removes error message text from log messages where JSON string marshalling failed to avoid possible leak of sensitive information.

update to logger redaction

---

v3/integrations/nrawssdk-v1/nrawssdk.go
v3/integrations/nrawssdk-v1/nrawssdk_test.go
v3/internal/awssupport/awssupport.go

Fixes #427 and #432. Sending the distributed trace headers to AWS is rather pointless, and can cause the request signature to be corrupted on retries. Also, previously the AWS request id and response status code were not being properly captured.
Note: Due to breaking changes in the v3/internal package, the new release of nrawssdk-v1 will depend on the new release of v3. Not sure how this is normally dealt with.

do not include distributed trace headers in AWS SDK requests

---

.github/workflows/ci.yaml
build-script.sh

Creates a new directive in the test matrix, "pin", that allows you to pin the version of a library imported during that test to a specific version. This is best used in cases where that specific test needs a version pin of something. Pins that affect a number of tests are cleaner to implement in the bash script directly.

Test Dependency Pinning

---

internal/sysinfo/memtotal_openbsd_amd64.go
internal/sysinfo/memtotal_openbsd_test.go
v3/internal/sysinfo/memtotal_openbsd_amd64.go
v3/internal/sysinfo/memtotal_openbsd_test.go

This adds `PhysicalMemoryBytes` functions and tests for OpenBSD.

Add support for OpenBSD

---

v3/integrations/nrpkgerrors/nrkpgerrors_test.go
v3/integrations/nrpkgerrors/nrpkgerrors.go
v3/newrelic/trace_observer_test.go

Fixes #409. nrpkgerrors.Wrap() now checks if the error it is passed has attributes, and if it does, copies them into the New Relic error it creates.

Handle attributes in nrpkgerrors

---

CHANGELOG.md
v3/go.mod
v3/integrations/nrgrpc/go.mod
v3/newrelic/version.go

* Changed dependency on gRPC from v1.27.0 to v1.39.0. This in turn changes gRPC's dependency on `x/crypto` to v0.0.0-20200622213623-75b288015ac9, which fixes a security vulnerability in the `x/crypto` standard library module. Fixes [issue #451](https://github.com/newrelic/go-agent/issues/451).
* Incremented version number of the `nrawssdk-v1` integration from v1.0.1 to v1.1.0 to resolve an incompatibility issue due to changes to underlying code.

grpc version update and nrawsdk-v1 version update

---

v3/go.mod
v3/internal/jsonx/encode.go
v3/newrelic/distributed_tracing.go
v3/newrelic/json_object_writer.go

This PR addresses [issue 505](https://github.com/newrelic/go-agent/issues/505) by replacing the more expensive standard library `json.Marshal` calls with faster internal ones.

Json speed issue 505

---

.github/workflows/ci.yaml
v3/go.mod
v3/integrations/nrmssql/README.md
v3/integrations/nrmssql/example/main.go
v3/integrations/nrmssql/go.mod
v3/integrations/nrmssql/nrmssql.go
v3/integrations/nrmssql/nrmssql_test.go

Added intergation for ms sql server
Added integration for ms sql server to show database transactions on new relic. I have used the similar approach which is used in other integrations. I have added the relevant unit test and example as well which I tested on my local with sql server.

Added integration for ms sql server with newrelic

---

v3/integrations/nrlambda/go.mod

This version has a fix that we need.
This PR resolved an issue in AWS's lambda runtime for Go: https://github.com/aws/aws-lambda-go/pull/313
It's present in 1.20.0, and we need that fix, or invocations just timeout.
While that fix happened a long time ago, I was a go novice at the time, and I'm only now figuring out how to get the dependency situation straitened out.

Require 1.20.0 of aws-lambda-go

---

CHANGELOG.md
GUIDE.md
README.md
v3/newrelic/version.go

* Logs in context now supported for zerolog.
* This is a quick way to view logs no matter where you are in the platform.
* Adds support for logging metrics which shows the rate of log messages by severity in the Logs chart in the APM Summary view. This is enabled by default in this release.
* Adds support for forwarding application logs to New Relic. This automatically sends application logs that have been enriched to power APM logs in context. This is disabled by default in this release. This will be on by default in a future release.
* To learn more about APM logs in context see the documentation [here](https://docs.newrelic.com/docs/logs/logs-context/logs-in-context).
* Includes the `RecordLog` function for recording log data from a single log entry
* An integrated plugin for zerolog …

updates to release 3.17.0 of the agent

---

v3/internal/connect_reply.go
v3/internal/connect_reply_test.go
v3/internal/limits.go
v3/newrelic/app_run.go
v3/newrelic/app_run_test.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_test.go
v3/newrelic/errors.go
v3/newrelic/harvest_test.go

- Users can use `newrelic.ConfigCustomInsightsEventsMaxSamplesStored()` to change the Harvest Limit to their choosing
- Increased Default Custom Events Harvest Limit from 10k to 30k
- Set a Max Custom Events Harvest Limit at 100k
- Changed static values of samples being stored to dynamic value 
-  Changed DT Spans being read from `event_harvest_config` to `span_event_harvest_config`

Harvest Limit Increase + Patch for DT Spans

---

v3/newrelic/transaction.go

This is a minor update to clarify the usage of the SetOption method for transactions.

clarified comment for txn.SetOption

---

v3/newrelic/code_level_metrics.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_test.go

Fixes [issue #551](https://github.com/newrelic/go-agent/issues/551) by changing the single `string` value for `Config.CodeLevelMetrics.IgnoredPrefix` to the `[]string` value `Config.CodeLevelMetrics.IgnoredPrefixes`. Adjusts associated option-setting functions to accept multiple `string` parameters. Deprecates the `IgnoredPrefix` field but uses its value if one is set to avoid breaking existing code.
Fixes [issue #550](https://github.com/newrelic/go-agent/issues/550) by correcting errors in package documentation.

Fix: CLM improvements

---

v3/examples/server/main.go
v3/newrelic/code_level_metrics.go
v3/newrelic/code_level_metrics_test.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_options_test.go
v3/newrelic/config_test.go
v3/newrelic/instrumentation.go
v3/newrelic/internal_txn.go

Updates and corrects CLM collection code.
Fixes [issue 557](https://github.com/newrelic/go-agent/issues/557) by correcting where we were unconditionally calling functions to resolve the code location even when code level metrics were disabled globally, as well as doing redundant work in some cases if the user passed their own code locations in. There was also a race condition and thread incompatibility for wrapped function handlers that has been corrected.
Now the agent will never try to resolve code locations unless explicitly asked to (e.g., by the user directly calling `ThisCodeLocation` or similar function), until it knows for sure it needs to collect CLM for that transaction. It will also look to see if code level metrics are locally suppressed (`WithoutCodeLevelMetrics()`) or …

Corrections to CLM data collection code

---

CHANGELOG.md
v3/newrelic/version.go

* Added `WithDefaultFunctionLocation` trace option. This allows the caller to indicate a fall-back function to use for CLM in case no other location was found first.
* Added caching versions of the code-level metrics functions `ThisCodeLocation` and `FunctionLocation` , and trace options `WithThisCodeLocation`  and  `WithFunctionLocation`. These improve performance by caching the result of computing the source code location, and reuse that cached result on all subsequent calls.
* Added a `WithCodeLevelMetrics` trace option to force the collection of CLM data even if it would have been excluded as being out of the configured scope. (Note that CLM data are _never_ collected if CLM is turned off globally or if the `WithoutCodeLevelMetrics` option was specified for the same transaction.)
* …

release notes and version increment for 3.18.2

---

CHANGELOG.md
v3/integrations/logcontext-v2/logWriter/go.mod
v3/integrations/logcontext-v2/nrwriter/LICENSE.txt
v3/integrations/logcontext-v2/nrwriter/go.mod
v3/integrations/logcontext-v2/nrwriter/nrwriter.go
v3/integrations/logcontext-v2/zerologWriter/go.mod
v3/newrelic/version.go

* Moved the v3/internal/logcontext/nrwriter module to v3/integrations/logcontext-v2/nrwriter
New Relic recommends that you upgrade the agent regularly to ensure that you’re getting the latest features and performance benefits. Additionally, older releases will no longer be supported when they reach end-of-life.
See the [Go Agent EOL Policy](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/) for details about supported versions of the Go Agent and third-party components.

Changelog and NrWriter Bump

---

v3/integrations/nrmysql/go.mod

Fixes #519 
not using this version of the sql driver may cause connection leaks

Fix #519: bump sql driver to v1.6.0

---

.github/workflows/ci.yaml
CHANGELOG.md
README.md
v3/build-script.sh
v3/go.mod
v3/integrations/nrawssdk-v2/go.mod
v3/integrations/nrecho-v4/go.mod
v3/integrations/nrgin/example/main.go
v3/integrations/nrgin/go.mod
v3/integrations/nrgin/nrgin.go
v3/integrations/nrgrpc/go.mod
v3/integrations/nrgrpc/nrgrpc_client_test.go
v3/integrations/nrgrpc/nrgrpc_server_test.go
v3/integrations/nrmongo/go.mod
v3/integrations/nrmysql/go.mod
v3/integrations/nrnats/go.mod
v3/integrations/nrnats/test/go.mod
v3/integrations/nrstan/go.mod
v3/newrelic/version.go

* Updated nrgin integration to more accurately report code locations when code level metrics are enabled.
* The Go Agent and all integrations now require Go version 1.17 or later.
* Updated minimum versions for third-party modules.
* nrawssdk-v2, nrecho-v4, nrgrpc, nrmongo, nrmysql, nrnats, and nrstan now require Go Agent 3.18.2 or later
* the Go Agent now requires protobuf 1.5.2 and grpc 1.49.0
* Internal dev process and unit test improvements.
New Relic recommends that you upgrade the agent regularly to ensure that you’re getting the latest features and performance benefits. Additionally, older releases will no longer be supported when they reach end-of-life.
We also recommend using the latest version of the Go language. At minimum, you should at least be using no version of Go older …

Release v3.19.2

---

v3/go.mod
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_test.go
v3/newrelic/environment.go
v3/newrelic/environment_test.go

This implements module dependency metrics in the Go Agent. This feature reports the application's dependencies when connecting to the New Relic service, allowing the customer to better manage dependencies and be aware of security vulnerabilities in libraries they use.
This version only collects the name and version number for each imported package.
Also introduces the ability to redact what modules were explicitly excluded by the user, and adds that capability to the Code Level Metrics capability as well.

Add Module Dependency Metrics to the Go Agent

---

v3/integrations/logcontext-v2/zerologWriter/zerolog-writer.go
v3/integrations/logcontext-v2/zerologWriter/zerolog-writer_test.go

In preparation for a more feature rich log data spec, this parser was built to be able to scan additional contextual vaule from a zerolog log message. This patch fixes a bug where it was unable to correctly parse the JSON value for strings with commas, numbers, or stack traces.

More Defensive zerologWriter parsing

---

.github/workflows/ci.yaml
v3/internal/connect_reply.go
v3/internal/limits.go
v3/newrelic/config_options.go
v3/newrelic/reservoir_limits_test.go

To help our customers see more of the custom events they're producing, the default Custom Events reservoir limit has been increased from 10,000 events per minute to 30,000 events per minute.

Default Custom Event Harvest Increase from 10,000 to 30,000 

---

.github/workflows/ci.yaml
v3/integrations/nrpgx5/README.md
v3/integrations/nrpgx5/example/pgx/main.go
v3/integrations/nrpgx5/example/pgxpool/main.go
v3/integrations/nrpgx5/go.mod
v3/integrations/nrpgx5/nrpgx5.go
v3/integrations/nrpgx5/nrpgx5_test.go
v3/integrations/nrpgx5/pgsnap_tracer_batch.txt
v3/integrations/nrpgx5/pgsnap_tracer_connect.txt
v3/integrations/nrpgx5/pgsnap_tracer_inpool.txt
v3/integrations/nrpgx5/pgsnap_tracer_trace_crud.txt

This PR are adding instrumentation for nrpgx/v5 (https://github.com/jackc/pgx)
The discussion about new tracing in pgx https://github.com/jackc/pgx/issues/1061.
Open Telemetry Implementation for this tracing feature https://github.com/exaring/otelpgx/blob/main/tracer.go
The pgx library has new tracing support in v5. Before pgx only support for logging that only provide us with duration of the operation. With this new tracing feature, we can create new Segment at `QueryStart` and End the Segment with `QueryEnd`
For passing the segment between `QueryStart` and `QueryEnd` we use `context.Context`. This folllow the implementation from open telemetry.
And for the `Host`, `Port` and `Database Name`, I try to follow `database/sql` implementation in `nrpq` and `nrpgx` by using BaseSegment.
To use …

adding nrpgx5 instrumentation tracer for github.com/jackc/pgx/v5

---

CHANGELOG.md
v3/go.mod
v3/newrelic/code_level_metrics.go
v3/newrelic/code_level_metrics_test.go

Updates to comply with new CLM agent specs relating to long fields.
No CLM field will be sent if it exceeds 255 characters.
All CLM fields will be suppressed if there isn't the minimum combination of useful fields that would fit in the 255 character limit.
This prevents truncated names from getting reported since they would be useless to code analysis.

Implement length limits for CLM attributes

---

CHANGELOG.md
README.md
v3/newrelic/version.go

Increments version info and updates changelog for 3.20.1 release.

release 3.20.1 changelog and version increment

---

v3/integrations/nrstan/test/go.mod

Affected of this `newrelic/go-agent` are vulnerable to Arbitrary File Write via Archive Extraction (Zip Slip) in the stream restore. This due to inadequate checks on the filenames within the archive file which can lead to a path traversal. It is exploited using a specially crafted zip archive, that holds path traversal filenames. When exploited, a filename in a malicious archive is concatenated to the target extraction directory, which results in the final path ending up outside of the target folder. For instance, a zip may hold a file with a "../../file.exe" location and thus break out of the target folder. If an executable or a configuration file is overwritten with a file containing malicious code, the problem can turn into an arbitrary code execution issue quite easily.
The following …

Update and Fixed Arbitrary File Write via Archive Extraction (Zip Slip)

---

v3/integrations/nrecho-v4/go.mod

Affected of this `newrelic/go-agent` are vulnerable to Open Redirect in handlers serving static directories via the `echo.StaticDirectoryHandler` handler. Labstack Echo v4.8.0 was discovered to contain an open redirect vulnerability via the Static Handler component. This vulnerability can be leveraged by attackers to cause a Server-Side Request Forgery (SSRF). 
```js
p = c.Request().URL.Path // path must not be empty.
if fi.IsDir() && p[len(p)-1] != '/' {
if fi.IsDir() && len(p) > 0 && p[len(p)-1] != '/' {
// Redirect to ends with "/"
return c.Redirect(http.StatusMovedPermanently, p+"/")
return c.Redirect(http.StatusMovedPermanently, sanitizeURI(p+"/"))
}
return c.File(name)
}
// Handle added routes based on trailing slash:
// 	/prefix  => exact route "/prefix" + any route "/prefix/*"
// …
```

Update and Fixed Labstack Echo Open Redirect 

---

v3/examples/server/main.go
v3/newrelic/errors_from_internal.go
v3/newrelic/harvest.go
v3/newrelic/harvest_test.go
v3/newrelic/internal_errors_stacktrace_test.go
v3/newrelic/internal_errors_test.go
v3/newrelic/internal_txn.go
v3/newrelic/intrinsics.go
v3/newrelic/metric_names.go
v3/newrelic/tracing.go
v3/newrelic/transaction.go
v3/newrelic/txn_trace.go

A new API has been added that will allow users to notice errors without triggering their error alerts or metrics: NoticeExpectedError() 
Fixes #161

Notice Expected Errors

---

CHANGELOG.md
CONTRIBUTING.md
README.md
v3/newrelic/version.go

3.20.2 Release

---

internal/collector.go
internal/collector_test.go
internal/compress.go
v3/newrelic/collector.go
v3/newrelic/collector_test.go
v3/newrelic/internal_app.go

We have been observing the memory increase in our Go applications for a long time. When We look at the cumulative increase of the memories used by the application with the memory dump method, We observed that the New Relic agent uses a lot of memory while doing gzip compression.
As a result, too much GC is running. You can visualize it by closing GOGC=off and defining GOMEMLIMIT this will avoid unnecessary GC, and will trigger the GC only if it's closed to the GOMEMLIMIT.
Issue: https://github.com/newrelic/go-agent/issues/619
Instead of creating a new gzip writer for every collect request, use common ones by using gzip writer sync pool.

Fix memory leak while compression

---

v3/integrations/nrawssdk-v1/go.mod

sends an unencrypted hash of the plaintext alongside the ciphertext as a metadata field. This hash can be used to brute force the plaintext, if the hash is readable to the attacker. AWS now blocks this metadata field, but older SDK versions still send it.

Patched unencrypted hash of the plaintext alongside the ciphertext as a metadata field

---

v3/integrations/nrmssql/README.md
v3/integrations/nrmssql/go.mod
v3/integrations/nrmssql/nrmssql.go

https://github.com/newrelic/go-agent/issues/618
Just changes package github.com/denisenkom/go-mssqldb to github.com/microsoft/go-mssqldb. Microsoft repo is a fork from denisenkom and is now the official package for mssql driver.

Change mssql driver from denisenkom to microsoft

---

v3/go.mod
v3/newrelic/application.go
v3/newrelic/attributes.go
v3/newrelic/attributes_from_internal.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/environment_test.go
v3/newrelic/error_events.go
v3/newrelic/error_group.go
v3/newrelic/errors_from_internal.go
v3/newrelic/errors_test.go
v3/newrelic/harvest_test.go
v3/newrelic/internal_test.go
v3/newrelic/internal_txn.go
v3/newrelic/stacktrace.go
v3/newrelic/stacktrace_test.go
v3/newrelic/tracing.go
v3/newrelic/transaction.go

This adds functionality to the agent that enables users to define a custom callback function that will be applied to all noticed errors in the agent. It must return a string value which will be used to categorize this error into an error group in New Relic One.

Error Group Callback and User Tracking

---

README.md
v3/integrations/nrredis-v9/LICENSE.txt
v3/integrations/nrredis-v9/README.md
v3/integrations/nrredis-v9/example/main.go
v3/integrations/nrredis-v9/go.mod
v3/integrations/nrredis-v9/nrredis.go
v3/integrations/nrredis-v9/nrredis_example_test.go
v3/integrations/nrredis-v9/nrredis_test.go

- https://github.com/redis/go-redis/blob/v9.0.1/CHANGELOG.md
- https://github.com/redis/go-redis/blob/v9.0.1/redis.go#L76-L115
The go-redis package was just moved into `redis` Github organization so the package was renamed from `github.com/go-redis/redis` to `github.com/redis/go-redis`. They also just released new major version (v9) with several breaking changes, notably to the hook system.
To ensure smooth upgrade from go-redis v8 to v9, a new integration code is needed.

feature: instrument go-redis v9

---

.github/workflows/ci.yaml

Avoid a mutual exclusion situation where the ubuntu latest and ubuntu 18.0.4 are expected as runtime versions, but can not be grouped. See https://github.com/orgs/community/discussions/26783 for details.

Run workflows on ubuntu-latest only

---

.github/workflows/ci.yaml
README.md
v3/integrations/nrredis-v9/LICENSE.txt
v3/integrations/nrredis-v9/README.md
v3/integrations/nrredis-v9/example/main.go
v3/integrations/nrredis-v9/go.mod
v3/integrations/nrredis-v9/nrredis.go
v3/integrations/nrredis-v9/nrredis_example_test.go
v3/integrations/nrredis-v9/nrredis_test.go

Submitting on behalf of @gunturaf. We merged #634 into master instead of develop, and had to undo. Merged PR's cannot be re-opened. 
Author: @gunturaf

Nrredis v9

---

CHANGELOG.md
v3/go.mod
v3/newrelic/version.go

* Corrects an error in the release process for 3.22.0.
We use the latest version of the Go language. At minimum, you should be using no version of Go older than what is supported by the Go team themselves.
See the [Go agent EOL Policy](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/) for details about supported versions of the Go agent and third-party components.

release 3.22.1

---

v3/integrations/nrsecurityagent/README.md
v3/integrations/nrsecurityagent/nrsecurityagent.go
v3/newrelic/internal_app.go

Disabling IAST if HighSecurity is enabled because in HighSecurity mode request parameters can't be collected and without request parameters, IAST won't be able to work properly.
reference: https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-configuration/#high_security
Disabling IAST if HighSecurity is enabled

Disable IAST if HighSecurity is enabled

---

v3/integrations/nrsecurityagent/README.md
v3/integrations/nrsecurityagent/go.mod
v3/integrations/nrsecurityagent/nrsecurityagent.go

- To completely disable security set NEW_RELIC_SECURITY_AGENT_ENABLED env to false. If the env is set to false, the security module and hooks are not loaded.
- Update default config YAML in README.md
- Updated go.mod in nrsecurityagent to point to the latest csec-go-agent version (v0.2.1)

Update handling for complete disabling of security agent.

---

v3/newrelic/serverless.go

Print the JSON payload that is generated when the go agent does a harvest in serverless mode. If the harvest contained no payload data, print a log line mentioning that.
This will help us troubleshoot serverless issues and bring us to parity with other language agents.

feat: enhance serverless debug logging

---

v3/integrations/nrpq/example/main.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_test.go
v3/newrelic/internal_txn.go
v3/newrelic/segments.go
v3/newrelic/sqlparse/sqlparse.go

Using `newrelic.ConfigDatastoreRawQuery(true)`, it is now possible to see full queries on New Relic dashboards. The default configuration (Using parameterized queries) will remain unchanged.

feat: Added new config option for raw SQL Queries

---

v3/newrelic/error_events.go

Fix for expected errors properly being marked in Errors Inbox on NR1

patch for expected errors

---

v3/newrelic/internal_txn.go
v3/newrelic/internal_txn_test.go
v3/newrelic/transaction.go

Partially satisfies [Issue 714](https://github.com/newrelic/go-agent/issues/714) by providing a `Name` getter method on `Transaction` to get the current transaction name.
Needs review to ensure adding this won't be a problem anywhere but looks to work reliably so far.
Adding this much toward the customer issue because it's simple enough to do now with minimal effort for the upcoming release until looking at the rest of the enhancement request in that issue at a later time.

added Name() transaction name getter function

---

v3/integrations/nrgrpc/nrgrpc_server.go
v3/newrelic/secure_agent.go

This is a couple of small fixes, one puts securityagent access behind a check that the agent is present to avoid unnecessary work. The other prevents a null pointer reference.

corrections to recent securityagent updates

---

v3/integrations/nrsecurityagent/go.mod
v3/integrations/nrsecurityagent/nrsecurityagent.go

- minor fix for complete security disable flag
- Update security agent version to the latest (v0.4.0)

Minor fixes for security agent.

---

CHANGELOG.md

Updates `CHANGELOG` to reflect a minor fix to the securityagent code that had previously been merged to `develop` but wasn't included in the changelog for this release.

corrected changelog for 3.25 release

---

CHANGELOG.md
v3/go.mod
v3/newrelic/version.go

* Corrects an error in the release process for 3.25.0.
We use the latest version of the Go language. At minimum, you should be using no version of Go older than what is supported by the Go team themselves.
See the [Go agent EOL Policy](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/) for details about supported versions of the Go agent and third-party components.

Release 3.25.1

---

v3/newrelic/version.go

* Extended implementation of the `nrpgx5` integration (now v1.2.0). This instruments Postgres database operations using the `jackc/pgx/v5` library, including the direct access mode of operation as opposed to requiring code to use the library compatibly with the standard `database/sql` library.
* See below for revised release notes for the 3.25.1 and the retracted 3.25.0 releases. We have clarified what was released at those versions; see also the revised notes for 3.22.0 and 3.22.1 for the same reason.
We use the latest version of the Go language. At minimum, you should be using no version of Go older than what is supported by the Go team themselves.
See the [Go agent EOL Policy](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/) for details about …

Release 3.26.0 version change

---

.github/workflows/ci.yaml
v3/build-script.sh

Fixes Broken tests in the go agent

Fix tests 3.27.0

---

v3/newrelic/error_events.go

The attribute error.expected should be a boolean, not a string. It is also good practice to use a constant value for the key.

Error Expected Bug

---

v3/go.mod
v3/newrelic/code_level_metrics.go

Fixes [Issue #640](https://github.com/newrelic/go-agent/issues/640).
Deprecates the CLM option to set `LocationOverride`, which forces the caller to do the work to determine the code location up-front even if CLM is disabled. Replaces this with a new function which registers a callback function, which the CLM code will call to get the function location from the user's code only if actually needed. The user's callback may use the existing caching code location functions to further optimize this.

CLM user code location callback alternative to LocationOverride option

---

v3/integrations/nrfasthttp/instrumentation.go
v3/integrations/nrgrpc/go.mod
v3/integrations/nrgrpc/nrgrpc_server.go
v3/integrations/nrmongo/nrmongo.go
v3/integrations/nrsecurityagent/go.mod
v3/integrations/nrsecurityagent/nrsecurityagent.go
v3/newrelic/sql_driver.go

**Bug Fixes**
- Incorrect query-type/commandName for mongo findAndModify case.
- Fixed for RXSS event for fastHttp.
- Minor fix for sql prepare statement.
- Incorrect server protocol/transport type in case of grpc.
- Updated csec-go-agent version to v0.6.0

Bug fixes for security agent

---

v3/integrations/nrsecurityagent/go.mod

The security agent is now at v1.0.0. This PR updates our dependency on it to that version.

update dependency on csec

---

v3/examples/server/Dockerfile

Since the simple server example in `v3/examples/server` is often used for testing the Go Agent in various scenarios and under various loads (as well as a conveniently small example to demonstrate how to instrument code), this PR adds a `Dockerfile` which provides for the easy creation of a ready-to-run instance of this instrumented example server in a Docker container.
The instructions needed to build the image and use it in testing are included as comments in the `Dockerfile` itself.

Dockerized example server for testing purposes

---

CHANGELOG.md
v3/newrelic/version.go

Version number bump and supporting information for the release.

Setup for release 3.31.0

---

v3/integrations/nrawsbedrock/go.mod
v3/integrations/nrawsbedrock/nrawsbedrock.go
v3/integrations/nropenai/LICENSE.txt

A few loose ends after the GA release of AI monitoring integrations:
- adds missing license file for `nropenai`
- adds note about other required configuration settings for `nrawsbedrock`
- changes `bedrockruntime.Client` parameter to a more general interface type

doc fixes and tweaks for AIM integrations

---

.github/workflows/ci.yaml
v3/integrations/logcontext-v2/nrslog/handler.go
v3/integrations/logcontext-v2/nrslog/handler_test.go

I would like to introduce a handler that takes new relic transaction data from context automatically.
It is quite a common pattern to inject the base slog logger instance to some piece of code only so to pass it to `nrslog.WithContext` to receive a handler that captures logs in context. I find this api to be a bit leaky and introducing noise. Especially that slog already has methods which make context available for handlers.
With introduction of this handler one now can set a slog instance relying on a NRHandler as default one and call it from anywhere, ensuring that log data with be passed to go-agent, as well as if the context contains transaction it will be linked. This is quite the case for http services which rely on `newrelic.WrapHandle`. This also decouples non infra/non …

feat: slog: automatically reference transaction from context

---

v3/internal/utilization/azure.go
v3/internal/utilization/utilization.go

Previously, when any Containerized Environments that aren't running on Azure get detected the go agent would output a Azure unauthorized utilization error. Now, if any containerized environments are detected, the error should not incorrectly be logged

Azure Utilization Detecting Bug

---

v3/integrations/logcontext-v2/nrzap/go.mod
v3/integrations/logcontext-v2/nrzap/nrzap.go
v3/integrations/logcontext-v2/nrzap/nrzap_test.go
v3/newrelic/expect_implementation.go

NrZap attributes fix

---

CHANGELOG.md
v3/newrelic/version.go

- Increased max span events default limit to 2,000 to align with agent specifications
- Added support for gRPC API endpoints and HTTP status codes in the nrsecurity integration
- Added feature to detect route of an incoming request for all supported frameworks in the nrsecurity integration.
- Updated support for latest New Relic Security Agent release.
- Fixed an issue with nrzap attributes not properly being forwarded
- Improved comments on nropenai
- Fixed a minor bug relating to ExpectStatusCodes in `app_run.go`
We use the latest version of the Go language. At minimum, you should be using no version of Go older than what is supported by the Go team themselves.
See the [Go agent EOL Policy](/docs/apm/agents/go-agent/get-started/go-agent-eol-policy) for details about supported versions …

release 3.33.1

---

v3/go.mod
v3/integrations/nrmssql/nrmssql.go
v3/newrelic/sql_driver.go
v3/newrelic/trace_observer.go
v3/newrelic/trace_observer_impl_test.go
v3/newrelic/trace_observer_test.go

Fixes #939.
As per the README, Go 1.18+ is already required. Thus version constraints for 1.9 and 1.10 are unnecessary. (And these currently cause issues with 1.23rc2 due to https://github.com/golang/go/issues/68658.)

remove all extraneous version constraints

---

v3/newrelic/attributes_from_internal.go
v3/newrelic/log_events_test.go

Running against the latest agent version [v3.34.0](https://github.com/newrelic/go-agent/releases/tag/v3.34.0)
w/ Logrus LogsInContext configured ([doc](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-go/#3-logrus))
Related to new functionality added in 
_Capture Log Attributes in the Agent_  https://github.com/newrelic/go-agent/pull/900
_Using Logrus attributes_ https://github.com/newrelic/go-agent/pull/937
Currently, when errors are logged with the Logs in Context integration, the type is emitted instead of the error string.  
```
log.WithError(fmt.Errorf("this is the error message")).Error("Something went wrong")
```
Console output:
> {"error":"this is the error message","level":"error","msg":"Something went wrong"}
NewRelic Log:
> …

 Use error.Error() string for log attributes

---

v3/go.mod
v3/newrelic/application.go
v3/newrelic/instrumentation.go
v3/newrelic/secure_agent.go

Corrects access to the internal `app.app.run` structure by protecting that access with a mutex, in order to prevent race conditions.

added mutex guards around appRun for code level metrics

---

v3/newrelic/internal_txn.go

Go 1.21 changed the behavior of `panic(nil)` in a way that was at odds with how the agent handled that case. This PR corrects for it by checking for the new return value from `recover()` introduced at 1.21 as well as the `nil` return value which go provided in previous versions.

Fix handling of panic(nil)

---

v3/integrations/logcontext-v2/zerologWriter/zerolog-writer.go
v3/integrations/logcontext-v2/zerologWriter/zerolog-writer_test.go

Fixes Issue #955 
The JSON parser used by zerologwriter wasn't able to cope with some patterns of input that were given to it, causing a runtime panic. This code change makes the parser more robust and avoids the panic condition that was occurring.

Fix zerologwriter json parser bug

---

v3/integrations/nrecho-v3/nrecho.go
v3/integrations/nrecho-v4/nrecho.go
v3/integrations/nrfasthttp/instrumentation.go
v3/integrations/nrgin/nrgin.go
v3/integrations/nrgorilla/nrgorilla.go
v3/integrations/nrgraphqlgo/nrgraphqlgo.go
v3/integrations/nrhttprouter/nrhttprouter.go
v3/integrations/nrsecurityagent/go.mod
v3/newrelic/instrumentation.go

Expanded security capabilities by adding support for Secure Cookie event reporting, providing detailed vulnerability information.
Enabled sharing of response headers with the CSEC-Security-Agent to extract cookie values from headers.

Enhanced Security Features

---

v3/integrations/nrawssdk-v2/example/main.go
v3/integrations/nrawssdk-v2/nrawssdk.go
v3/integrations/nrawssdk-v2/nrawssdk_test.go

When testing the nrawssdk-v2 integration along with nrlambda I found out that the provided method of injecting the middleware to APIOptions does not work (no trace is seen for any aws call), what worked was to use the optFns param.
In this PR I'm only changing the documentation and example to reflect what has been working, but maybe you'd want to expand on it to add an exported function that can be used as an optFn ?
Also I could not find how to make the test fail as I'm not familiar enough with the internals.

nrawssdk-v2: fix usage examples of nrawssdk.AppendMiddlewares

---

.github/workflows/ci.yaml

Fixes Issue #946 by updating the most recent golang versions to test in our CI workflow.

946 workflow correction - versions of golang to test in CI

---

v3/internal/trace_id_generator.go
v3/internal/trace_id_generator_test.go

Related-to: https://github.com/newrelic/go-agent/issues/767
Tried out various improvements for the linked issue, this PR improves the performance of the trace ID generation by doing the hex encoding in-place and avoiding an allocation. We see this function appearing in a high-throughput system, and hope that making it faster will also help us understand our own performance better.
benchstat for allocation avoidance:
```
goos: linux
goarch: amd64
pkg: github.com/newrelic/go-agent/v3/internal
cpu: AMD Ryzen 9 7940HS w/ Radeon 780M Graphics     
│ before.txt  │              after.txt              │
│   sec/op    │   sec/op     vs base                │
TraceIDGenerator-16           43.33n ± 3%   30.85n ± 1%  -28.81% (p=0.000 n=10)
TraceIDGeneratorParallel-16   71.23n ± 4%   60.40n ± 2% …
```

Improve performance of trace id generation

---

v3/newrelic/internal_test.go
v3/newrelic/internal_txn.go
v3/newrelic/internal_txn_test.go

Fixes [issue 975](https://github.com/newrelic/go-agent/issues/975) by removing the special handling that was wrapped around instrumented functions that experience a `panic(nil)`. Previously the code sought to keep the pre-Go-1.21 behavior of not propagating nil panics, but a better approach is to not treat them any differently than other panics.

Remove special handling of panic(nil)

---

v3/integrations/nrecho-v3/nrecho.go
v3/integrations/nrecho-v4/nrecho.go
v3/integrations/nrgin/nrgin.go
v3/integrations/nrgorilla/nrgorilla.go
v3/integrations/nrgraphqlgo/nrgraphqlgo.go
v3/integrations/nrhttprouter/nrhttprouter.go
v3/integrations/nrsecurityagent/README.md
v3/integrations/nrsecurityagent/go.mod
v3/integrations/nrsecurityagent/nrsecurityagent.go
v3/newrelic/instrumentation.go
v3/newrelic/internal_response_writer.go
v3/newrelic/internal_txn.go
v3/newrelic/transaction.go

- Added a new config for **IAST CI/CD** and **Scan Controllers** changes released in CSEC Agent Release v1.6.0
Configuration via yaml:
```yaml
iast_test_identifier: 'run-id'
scan_controllers:
scan_instance_count:  0 # Values are 1 or 0, 0 signifies run on all application instances
```
- Added CSEC instrumentation to support GraphQL.
- Updated several `SendEvent` API calls and included `trace.id` as a parameter.

New feature and optimizations for security agent 

---

v3/go.mod
v3/newrelic/transaction.go
v3/newrelic/transaction_test.go

These changes add logic and tests that verify that all methods called on new relic transactions gracefully return when the transaction object is nil.

prevent all transaction methods from nil transaction errors

---

v3/newrelic/internal_txn.go
v3/newrelic/internal_txn_test.go
v3/newrelic/transaction.go
v3/newrelic/transaction_test.go

- Issue: [#995](https://github.com/newrelic/go-agent/issues/995)
This pull request introduces a new `IsEnded()` method for the `Transaction` type. It addresses the issue raised in [#995](https://github.com/newrelic/go-agent/issues/995) where there was no straightforward way to determine if a transaction has ended.
**Changes include:**
- **New Method Implementation:**  
The `IsEnded()` method has been added to check the internal transaction state. It ensures that a transaction is considered ended if it is nil, if its thread is nil, or if the underlying transaction's `finished` flag is set.
```go
func (t *Transaction) IsEnded() bool {
if t == nil || t.thread == nil || t.thread.txn == nil {
return true
}
return t.thread.txn.finished
}
- **Unit Tests:**
Unit tests have been added to verify …
```

feat(transaction-is-ended): add IsEnded() method (#995)

---

.github/workflows/ci.yaml
v3/integrations/nrgochi/example/main.go
v3/integrations/nrgochi/go.mod
v3/integrations/nrgochi/nrgochi.go
v3/integrations/nrgochi/nrgochi_test.go

Go Chi Integration Support via Middleware

Go Chi Support

---

v3/integrations/nrredis-v9/go.mod
v3/integrations/nrredis-v9/nrredis.go
v3/integrations/nrredis-v9/nrredis_db_test.go
v3/integrations/nrredis-v9/util/empty_db.go

Addresses [Issue 1005](https://github.com/newrelic/go-agent/issues/1005).
This wasn't actually a bug *per se*, but the implementation of our agents currently don't include Redis parameters normally when reporting datastore telemetry since we can't necessarily assume they are the same sorts of things as, say, a parameterized query in a SQL database operation where we can report the parameterized query without the parameters. In this case, the key of a Redis operation might contain sensitive information depending upon how a particular database is organized. Generalizing further, the Redis database operations themselves comprise a large number of varied requests between client and server which overall have their 2nd data field as the interesting "key" or "id" value to report but not **all** …

redis-v9 datastore enhancements

---

CHANGELOG.md

Fixes [Issue 1018](https://github.com/newrelic/go-agent/issues/1018): URLs for EOL policy in changelog were missing domain name, causing them to be incorrectly interpreted relative to github site root, instead of New Relic documentation site.

fix broken EOL policy link

---

v3/integrations/logcontext-v2/nrslog/handler_test.go
v3/newrelic/attributes_from_internal.go
v3/newrelic/attributes_test.go
v3/newrelic/expect_implementation.go

support time objects for attribute values

---

v3/integrations/logcontext-v2/nrslog/handler.go
v3/integrations/logcontext-v2/nrslog/handler_test.go

Fix: log-context linking metadata can only be stored in the message of a log, not as an attribute

move linking metadata to the log message

---

v3/integrations/logcontext-v2/nrslog/example/main.go

nrslog in logs in context used a deprecated version of the nrslog API. We update the example to reflect better how to use it using the new API so that users can reference it and integrate the new API in their code.

Update nrslog example

---

v3/internal/tools/interface-wrapping/driver_conn.json
v3/newrelic/sql_driver_optional_methods.go

N/A
The nrmysql driver in newrelic/go-agent does not properly handle connection reuse in case of last query was errored when MySQL closes an idle connection and application try to reuse it, This leads to a "commands out of sync" error when the same connection is used again.
Steps to Reproduce
The following test program demonstrates the issue:
```
package main
import (
"database/sql"
"fmt"
"time"
_ "github.com/go-sql-driver/mysql"
_ "github.com/newrelic/go-agent/v3/integrations/nrmysql"
)
func main() {
mysqlConnString := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local", "user", "pass", "127.0.0.1", "3306", "db_name")
mdb, err := sql.Open("nrmysql", mysqlConnString)
fmt.Println("mysql open error:", err)
mdb.Ping()
fmt.Println("ping error:", err)
// This query will …
```

added SessionResetter into driver_conn optional interfaces

---

v3/integrations/nrnats/test/go.mod
v3/integrations/nrsnowflake/go.mod
v3/integrations/nrstan/examples/go.mod
v3/newrelic/app_run.go
v3/newrelic/config.go
v3/newrelic/config_options.go
v3/newrelic/config_test.go
v3/newrelic/harvest.go
v3/newrelic/log_events.go
v3/newrelic/metric_names.go

https://new-relic.atlassian.net/browse/NR-354877
Added Custom Attributes via environment variable `NEW_RELIC_APPLICATION_LOGGING_FORWARDING_CUSTOM_ATTRIBUTES` or programmatically. Format of key/value is `key1:val1;key2:val2;....`

feat: Add logging custom attributes

---

v3/internal/utilization/utilization.go

feat: Add mutex for thread-safe access to vendors data

---

.github/workflows/test-pull-request.yml
Dockerfile
docker-compose.yml

Upgrade support for building and testing go 1.24 and 1.25.
Deprecate testing support for 1.23.

chore: add support for go 1.25
