v3/newrelic/internal_distributed_trace_test.go
GO-315
This test is intended to verify that we are properly handling duplicate tracestate headers.
=> add tracestate duplicate test

CHANGELOG.md, v3/newrelic/version.go
Also adds changelog for span parentage.
=> Update versions for v3.8.1 release.

v4/newrelic/application.go, v4/newrelic/segments.go, v4/newrelic/segments_test.go, v4/newrelic/transaction.go
This PR adds support for basic `Segment`s and `Transaction.NewGoroutine`.
Not included is support for other segment types.
=> Add Segment and NewGoroutine support.

v4/internal/context.go, v4/newrelic/context.go, v4/newrelic/context_test.go, v4/newrelic/segments_test.go, v4/newrelic/transaction.go
This PR implements the contents of `context.go` and adds a couple of tests.
=> Implement context related APIs.

v4/integrations/nrawssdk-v1/nrawssdk_test.go, v4/integrations/nrawssdk-v2/nrawssdk_test.go, v4/integrations/nrgrpc/nrgrpc_server_test.go, v4/integrations/nrmicro/nrmicro_test.go, v4/internal/otel_expect.go, v4/newrelic/segments.go, v4/newrelic/segments_test.go, v4/newrelic/transaction.go, v4/newrelic/transaction_test.go
This pull request implements two more Expect methods. This work also uncovered some bugs! 🎉 I fixed those in here as well. I will comment throughout the code to help with review.
=> Implement ExpectMetrics and ExpectMetricsPresent.

v4/internal/expect.go, v4/internal/otel_expect.go, v4/newrelic/segments_test.go, v4/newrelic/transaction_test.go
Now that we have this super nice way of testing integrations, we should use it in the `newrelic` package as well. I think this really cleans up the tests and makes it much easier to read!
=> Use the expect app in newrelic package tests.

v4/examples/otel/go.mod, v4/go.mod, v4/newrelic/application.go, v4/newrelic/config_options.go, v4/newrelic/log.go, v4/newrelic/segments.go, v4/newrelic/transaction.go
This is currently a WIP. Still to work on ensuring we don't panic when the logger is nil (preferably in a more elegant way than the way I started addressing it)
=> Add logging to the shim

CHANGELOG.md, v3/newrelic/version.go
Getting ready to release v 3.9.0
=> Updating version #

CHANGELOG.md, v3/newrelic/version.go
Thanks to @jodeev for making these release notes much better than they were before.
=> Release notes v3.10.0

v3/integrations/nrredis-v8/LICENSE.txt
Added license file for redis v8 integration.
=> added license file to redis v8 integration

CHANGELOG.md, v3/newrelic/version.go
Here's a new CHANGELOG.md for us all to review in anticipation of the March Go Agent release.
=> Release notes v3.11.0

CHANGELOG.md
@urbiz-nr made edits to these before putting them onto the New Relic documentation site. This PR just backports her changes to our CHANGELOG.md file.
=> Backported Anna Urbiztondo's changes

CHANGELOG.md, v3/newrelic/version.go
Updating version number and changelog for the 3.13.0 release.
=> changelog, version for 3.13.0

v3/integrations/nrawssdk-v2/example/main.go
=> Fixed typo in variable

v3/integrations/nrgrpc/nrgrpc_server.go, v3/integrations/nrgrpc/nrgrpc_server_test.go
Corrects a typo that caused failing tests in the nrgrpc integration
=> correct typo in testcases

CHANGELOG.md, v3/newrelic/version.go
=> patch release 3.14.1 to fix nrgrpc integration test typo

CHANGELOG.md
Adds information about the nrgrpc update to changelog.
=> added note about nrgrpc version number bump

CHANGELOG.md, v3/newrelic/version.go
This PR updates the version information for the 3.16.0 release.
=> Release 3.16.0 

CHANGELOG.md
=> Release 3.16.0 additional changes

v3/integrations/nrawssdk-v1/go.mod
Corrects PR 525 by removing unrelated code from another PR.
=> update aws gomod

CHANGELOG.md, v3/newrelic/version.go
Release 3.18.0 of the Go Agent
=> Release v3.18.0

CHANGELOG.md
Correction to CHANGELOG to reflect current state of CodeStream integration availability.
=> updated changelog CodeStream note

.github/workflows/ci.yaml, v3/integrations/logcontext-v2/nrzerolog/go.mod, v3/integrations/logcontext-v2/nrzerolog/hook.go, v3/integrations/logcontext-v2/nrzerolog/hook_test.go, v3/newrelic/expect_implementation.go
Adds test for nrlogrus, and runs the new test in CI
=> Logcontext v2 tests

CHANGELOG.md, v3/newrelic/version.go
Sets the CHANGELOG and version file for 3.19.2
=> Release 3.19.2

README.md, v3/go.mod
Changed the README file to note dependency on Go 1.17.
=> Release 3 19 2 Readme update

v3/newrelic/log_event.go
=> Fix typos in log_event.go

v3/newrelic/config_options.go
The IgnoredPrefix and PathPrefix options now take multiple arguments and write into fields with pluralized names (Prefixes). This PR deprecates the old, non-plural option-setting names and introduced pluralized ones to be more consistent.
=> Pluralize "*Prefixes" consistently in CLM-related option setting functions

v3/newrelic/config.go, v3/newrelic/config_options.go, v3/newrelic/config_options_test.go, v3/newrelic/config_test.go
Adds:
- Env variables for application logging feature flags
- Log forwarding set to true by default
=> enable application log forwarding by default

v3/internal/connect_reply.go, v3/newrelic/app_run.go, v3/newrelic/app_run_test.go, v3/newrelic/config.go, v3/newrelic/config_test.go, v3/newrelic/internal_test.go, v3/newrelic/internal_txn.go, v3/newrelic/metrics.go
Adds:
- Expected Errors for HTTP Status Codes
- Server side config for expected HTTP Status Codes
- Faster Expected and Ignored Status Code Check times
co-author: @mirackara
=> Expect Errors for Status Codes

v3/integrations/nrpgx5/nrpgx5.go
For applications handling sensitive data, its useful to be able to configure integrations to *not* send database query parameters upstream to New Relic.
This PR adds a `SendQueryParameters` flag to the `Tracer` struct, which controls whether `QueryParameters` are set on the Segment. By default, this is set to true, to preserve existing functionality.
=> Add SendQueryParameters flag to nrgpx5 to selectively enable sending database query parameters

.github/workflows/auto_assign.yml, .github/workflows/autoassign.yml
https://github.com/marketplace/actions/auto-assign-action
=> feat(auto-assign-bot): Add github action to auto assign reviewers to PRs

.github/auto_assign.yml
=> fix auto assign action I hope

v3/integrations/nrgrpc/go.mod
=> Revert "Bump golang.org/x/text from 0.3.3 to 0.3.8 in /v3/integrations/nrgrpc"

v3/integrations/nrlogrus/go.mod, v3/integrations/nrlogrus/nrlogrus_test.go
Divided single test case up into multiple test cases for each logrus log level. Added Additional tests for ConfigLogger & ConfigStandardLogger
=> Full test coverage for logrus integration

v3/integrations/nrlogxi/go.mod, v3/integrations/nrlogxi/nrlogxi_test.go
=> Update testing suite for nrlogxi

.github/workflows/ci.yaml, v3/integrations/logcontext-v2/nrzap/LICENSE.txt, v3/integrations/logcontext-v2/nrzap/example/main.go, v3/integrations/logcontext-v2/nrzap/go.mod, v3/integrations/logcontext-v2/nrzap/nrzap.go, v3/integrations/logcontext-v2/nrzap/nrzap_test.go
Automatically capture logs in zap with a wrapped zap.Core object, and send them to New Relic.
=> Feat: zap logs in context

.github/workflows/ci.yaml, v3/integrations/nrnats/go.mod, v3/integrations/nrnats/nrnats_test.go
Fix for nrnats not properly displaying code coverage
=> nrnats test fixes

CHANGELOG.md, v3/newrelic/version.go
=> oops release 3.22.0

.github/workflows/ci.yaml, v3/build-script.sh, v3/integrations/nrnats/go.mod, v3/newrelic/trace_observer_impl_test.go, v3/newrelic/trace_observer_test.go
Goodie-box of test improvements 🍾🎆🥳  
- Removed timeouts on two tests in trace observer.
- Added nrsarama package testing to github 
- Removed extratesting for nrlogrus test
- Removed arm64 go1.17 test
- Bumped nrnats test to go1.19
=> Multiple Github CI test improvements

v3/newrelic/internal_txn.go, v3/newrelic/transaction.go
- added fix for data race with NewGoroutine.
https://github.com/newrelic/go-agent/issues/748
=> Fix for data race with NewGoroutine

.github/workflows/ci.yaml
Fixes some CI testing (versions, mostly)
=> update ci tests to new go version, logrus

v3/newrelic/transaction.go
Fix for issue 822
https://github.com/newrelic/go-agent/issues/822
=> Fix for turn nil body into non nil body (issues 822)

v3/internal/expect.go, v3/newrelic/errors_from_internal.go, v3/newrelic/errors_test.go, v3/newrelic/harvest_test.go, v3/newrelic/internal_txn.go, v3/newrelic/slow_queries_test.go, v3/newrelic/tracing.go, v3/newrelic/txn_trace.go
=> Always Link Transaction IDs to Traces

v3/newrelic/collector.go, v3/newrelic/collector_test.go, v3/newrelic/internal_app.go, v3/newrelic/internal_app_test.go
=> more robust solution for obfuscation

v3/integrations/nrsecurityagent/go.mod, v3/integrations/nrsecurityagent/nrsecurityagent.go, v3/newrelic/config.go, v3/newrelic/secure_agent.go
- Added handling to post security configuration on UI.
=> Post security configuration on UI

v3/internal/cat/headers.go, v3/internal/cat/synthetics.go, v3/internal/cat/synthetics_test.go, v3/newrelic/cross_process_http.go, v3/newrelic/txn_cross_process.go, v3/newrelic/txn_cross_process_test.go, v3/newrelic/txn_events.go
Adds `X-Newrelic-Synthetics-Info` header handling and metadata.
=> Synthetics Info Extension

v3/integrations/logcontext-v2/nrslog/example/main.go, v3/integrations/logcontext-v2/nrslog/go.mod, v3/integrations/logcontext-v2/nrslog/handler.go, v3/integrations/logcontext-v2/nrslog/handler_test.go, v3/integrations/logcontext-v2/nrslog/writer.go
Automatically Capture Logging data from `slog` using this new instrumentation package.
=> New Relic Slog Instrumentation

v3/integrations/nrawsbedrock/example/main.go, v3/integrations/nrawsbedrock/go.mod, v3/integrations/nrawsbedrock/nrawsbedrock.go, v3/newrelic/attributes_from_internal.go, v3/newrelic/custom_event.go, v3/newrelic/internal_app.go
This PR includes a few post-testing adjustments to the bedrock implementation.
=> bedrock tweaks after testing

v3/integrations/nropenai/examples/chatcompletionstreaming/chatcompletionstreaming.go, v3/integrations/nropenai/nropenai.go, v3/integrations/nropenai/nropenai_test.go
=> openai changes

v3/internal/utilization/addresses.go
Removed old `newrelic.com` hostname with `collector.newrelic.com`
=> Updated host to collector

v3/integrations/nropenai/examples/chatcompletionstreaming/chatcompletionstreaming.go, v3/integrations/nropenai/nropenai.go, v3/integrations/nropenai/nropenai_test.go
=> Openai bug squash

v3/integrations/nropenai/nropenai.go
=> finish reason string fix

v3/integrations/nropenai/nropenai_test.go
=> Add request.model attribute to NRCreateChatCompletion test

README.md
=> Add AI integration packages to README

v3/newrelic/version.go
* Updates to support for the New Relic security agent to report API endpoints.
* Adds new wrapper function for the `nrecho`, `nrgin`, and `nrgorilla` integrations.
* Handler to take New Relic transaction data from context automatically when using `nrslog` integration (thanks, @adomaskizogian!) 
* Adds missing license file to the `nropenai` integration.
* Changes `*bedrockruntime.Client` parameters in `nrawsbedrock` integration to use a more general interface type, allowing the use of custom types which extend the bedrock client type.
* Fixes `pgx5` pool example
* Updated unit tests to check `Transaction.Ignore`
* Updated `nrzap` unit tests to add background logger sugared test case.
=> release 3.32.0

CHANGELOG.md
=> adds support statement to release notes

v3/integrations/nrecho-v3/nrecho.go
Fix for correct struct field name for echo version v3.2.2+
See [here](https://pkg.go.dev/gopkg.in/labstack/echo.v3@v3.2.2#Route) for documentation related to echo version v3.2.2 and above.
For echo version up to v3.2.1:
```
type Route struct {
Method  string `json:"method"`
Path    string `json:"path"`
Name  string `json:"name"`
}
```
See [here](https://pkg.go.dev/gopkg.in/labstack/echo.v3@v3.2.1#Route) for documentation related to echo version v3.2.1.
```
type Route struct {
Method  string `json:"method"`
Path    string `json:"path"`
Handler string `json:"handler"`
}
```
=> Fix for correct struct field name for echo version v3.2.2+

CHANGELOG.md, v3/newrelic/version.go
Updates version and release notes for v3.33.0 release.
=> release 3.33.0

v3/newrelic/config_test.go
=> Add ZapLogger attributes frontloading to config_test.go

v3/integrations/nrecho-v3/nrecho.go, v3/integrations/nrecho-v4/nrecho.go, v3/integrations/nrfasthttp/instrumentation.go, v3/integrations/nrgin/nrgin.go, v3/integrations/nrgorilla/nrgorilla.go, v3/integrations/nrgrpc/nrgrpc_server.go, v3/integrations/nrhttprouter/nrhttprouter.go, v3/integrations/nrsecurityagent/go.mod, v3/newrelic/instrumentation.go, v3/newrelic/internal_response_writer.go, v3/newrelic/internal_txn.go, v3/newrelic/secure_agent.go, v3/newrelic/transaction.go
Added following chnages required by csec agent
* Added support to detect gRPC API endpoint.
* Added feature to detect route of an incoming request for all supported frameworks.
* Added support to send HTTP status code.
=> Changes Required by CSEC Agent

v3/newrelic/app_run.go
Addresses https://github.com/newrelic/go-agent/issues/918
=> Typo fix in app run

v3/integrations/nrecho-v3/nrecho.go, v3/integrations/nrecho-v4/nrecho.go, v3/integrations/nrfasthttp/instrumentation.go, v3/integrations/nrgin/nrgin.go, v3/integrations/nrgorilla/nrgorilla.go, v3/integrations/nrgrpc/nrgrpc_server.go, v3/integrations/nrhttprouter/nrhttprouter.go, v3/integrations/nrmicro/go.mod, v3/integrations/nrstan/go.mod, v3/integrations/nrstan/test/go.mod, v3/newrelic/instrumentation.go
Adds a few missing checks on top of the latest csec agent updates.
=> corrections to csec updates

v3/integrations/logcontext-v2/nrslog/example/main.go, v3/newrelic/internal_app.go, v3/newrelic/log_event.go
also fixed minor typo in nrslog
=> Fixed an issue where logrus would not return logs if the application was shut down

.github/workflows/ci.yaml, README.md, v3/integrations/nrslog/LICENSE.txt, v3/integrations/nrslog/README.md, v3/integrations/nrslog/example_test.go, v3/integrations/nrslog/go.mod, v3/integrations/nrslog/nrslog.go
This change adds integration with standard `log/slog` package for agent logs.
=> Add log/slog support for agent logs

v3/integrations/logcontext-v2/nrlogrus/formatter.go, v3/integrations/logcontext-v2/nrlogrus/formatter_test.go
Adds attribute collection to logrus logcontext-v2
Link to #883
=> Logrus attributes

v3/go.mod
=> Update go.mod protobuff

v3/go.mod
=> Revert "Update go.mod protobuff"

CHANGELOG.md, v3/newrelic/version.go
Prepare the go agent for release 3.34.0
=> Release prep

v3/integrations/nrzerolog/example_test.go, v3/integrations/nrzerolog/go.mod
Fixes issue #950 
There was an error in the `import` statement in the example file for this integration.
=> 950 zerolog import fix

v3/integrations/nrlogxi/nrlogxi.go, v3/newrelic/utilities.go
Corrects integer size issues detected by automated code scans.
=> fix integer size issues

v3/integrations/logcontext-v2/nrslog/LICENSE.txt, v3/integrations/nramqp/LICENSE.txt, v3/integrations/nrfasthttp/LICENSE.txt, v3/integrations/nrmssql/LICENSE.txt
=> Fix missing license files in integration packages

v3/integrations/logcontext-v2/nrzap/nrzap.go
Adds caveat to API docs about local log decoration in zap integration.
=> caveat added to zap integration docs

CHANGELOG.md, v3/newrelic/version.go
=> version changes

v3/integrations/nrgochi/LICENSE.txt
=> Go chi license file

v3/integrations/nrgochi/example/main.go
=> remove possible csrf example

.github/workflows/ci.yaml, codecov.yml, run-tests.sh, v3/integrations/logcontext-v2/nrzap/nrzap_test.go, v3/integrations/nrsnowflake/go.mod
=> Switch to GitHub Actions Arm Runners

v3/integrations/nrfiber/go.mod, v3/integrations/nrgochi/go.mod
=> dependabot upgrades

v3/integrations/nrpgx5/nrpgx5.go
=> enhance query parameter representation in nrpgx5 integration

CHANGELOG.md, v3/integrations/nrconnect/nrconnect_doc.go, v3/integrations/nrconnect/nrconnect_test.go, v3/integrations/nrpgx5/nrpgx5_test.go, v3/newrelic/version.go
=> Release 3.40.0

v3/internal/awssupport/awssupport_test.go, v3/internal/utilization/utilization.go
=> Revert utilization.go and awssupport_test.go files 

v3/go.mod, v3/newrelic/version.go
=> retract v3.40.0
